services:
  fluxer-bot:
    container_name: fluxer-bot-host2
    env_file:
      - .env.host2
    depends_on: {}
    networks:
      - fluxer-bot_default

networks:
  fluxer-bot_default:
    external: true
